#!/usr/bin/env bash
# Configure Nginx to run as nginx user and listen on port 8080

sed -i 's/^user .*/user nginx;/' /etc/nginx/nginx.conf
sed -i 's/listen 80;/listen 8080;/' /etc/nginx/sites-available/default
sed -i 's/listen \[::\]:80;/listen \[::\]:8080;/' /etc/nginx/sites-available/default
service nginx restart
pgrep -a nginx
ss -tulnp | grep 8080
