#!/usr/bin/env bash
# Quickly makes Nginx serve on port 80 and then stops it
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx start
curl -s 0:80 > /dev/null
service nginx stop
